app/accounts/__init__.py
from flask import Blueprint

account = Blueprint('account', __name__)

from . import views

app/accounts/views.py
from flask import flash, redirect, render_template, url_for, request,render_template_string
from flask_login import login_required, login_user, logout_user, current_user
from app import db, login_manager

from . import account

from ..forms import EditUser

@account.route('/user')
@login_required
def account_user():
    return render_template('pages/account.jinja2', user=current_user)

@account.route('/user/edit', methods=['GET', 'POST'])
@login_required
def edit_user():
    form = EditUser()
    if form.validate_on_submit():
        current_user.last_name = form.last_name.data
        current_user.first_name = form.first_name.data
        current_user.address = form.address.data
        current_user.email = form.email.data
        current_user.phone = form.phone.data
        current_user.birthday = form.birthday.data
        db.session.commit()
        flash('Your changes have been saved.','success')
        return redirect(url_for('account.account_user'))

    elif  request.method == 'GET':
        form.last_name.data = current_user.last_name
        form.first_name.data = current_user.first_name
        form.address.data = current_user.address
        form.email.data = current_user.email
        form.phone.data = current_user.phone
        form.birthday.data = current_user.birthday

    return render_template('edit/edit_user.jinja2' , form=form)

app/templates/pages/_reglement.html
<div class="container">
  <div class="row home_intro">
    <div class="home_intro-text col-sm-11">
      <h1>Bienvenue sur FestiVOLS !&nbsp;</h1>
      <h2>L&rsquo;app de coordination garantie sans feuille EXCEL !</h2>


      <p>Bienvenue sur le portail du festival <strong>YesterdayWorld.</strong>&nbsp;Afin de pouvoir cr&eacute;er votre compte, veuillez prendre connaissance du pr&eacute;sent r&egrave;glement.</p>
      <p>Merci pour l'int&eacute;r&ecirc;t que tu portes au festival&nbsp;<strong>YesterdayWorld</strong> ! Nous avons h&acirc;te que rejoigne notre belle et grande famille de b&eacute;n&eacute;vole qui s'est construite avec les ann&eacute;es et une coordination sans faille !</p>
      <p>En tant que b&eacute;n&eacute;vole, tu rejoindras une seule &eacute;quipe, celle-ci effectuera des shifts constitu&eacute;s d'une t&acirc;che, d'un emplacement et d'un horaire pr&eacute;cis. T&acirc;che d'&ecirc;tre pr&eacute;sent cinq minutes &agrave; l'avance au minimum afin de garantir un roulement parfait.</p>
      <hr>
    </div>
  </div>
  <div class="row home_list">
    <div class="home_list-task col-sm-6">
      <p>Les t&acirc;ches &agrave; r&eacute;aliser durant le festival :</p>
      <ul>
        <li>Aide &agrave; la durabilit&eacute; et l&rsquo;&eacute;cologie du festival</li>
        <li>Accueil des festivaliers aux entr&eacute;es</li>
        <li>Accompagnement et service aupr&egrave;s du public &agrave; mobilit&eacute; r&eacute;duite</li>
        <li>Prestation libre, aide dans tous les secteurs en cas de besoin</li>
        <li>Organisation des parkings du festival</li>
        <li>Animation d&rsquo;espaces au Wallifornia Park</li>
        <li>Aide au restaurant des techniciens</li>
        <li>Accueil des festivaliers au camping</li>
        <li>Aide au VIP</li>
        <li>Animation et gestion de l'espace b&eacute;n&eacute;vole</li>
        <li>Aide au merchandising</li>
        <li>Renfort aux diff&eacute;rents bars du festival</li>
        <li>Renfort &agrave; d'autres d&eacute;partements &agrave; venir</li>
      </ul>
      <hr>
      <p style="text-align:center;"><img src="https://media.giphy.com/media/106QCYtKPDeIjm/giphy.gif" alt="Image animée tirée du film Hunger Games avec I volunteer" /></p>
    </div>
    <div class="home_list_others col-sm-6">
      <p>Les conditions pour &ecirc;tre b&eacute;n&eacute;vole :</p>
      <ul>
        <li>&Ecirc;tre &acirc;g&eacute; d&rsquo;au moins 16 ans</li>
        <li>&Ecirc;tre s&eacute;rieux, respectueux et ponctuel</li>
        <li>Fournir les prestations pour lesquelles tu t'es engag&eacute;</li>
        <li>Tu devras porter ton T-shirt b&eacute;n&eacute;vole pendant tes heures de prestation et uniquement pendant ces heures-l&agrave;</li>
      </ul>
      <hr>
      <p>Pour t'inscrire, tu dois fournir :</p>
      <ul>
        <li>Nom</li>
        <li>Pr&eacute;nom</li>
        <li>date de naissance</li>
        <li>adresse mail</li>
        <li>num&eacute;ro de t&eacute;l&eacute;phone</li>
        <li>situation professionnelle au moment du festival</li>
        <li>Num&eacute;ro de registre national ou CNI (pour les non-Belges)</li>
        <li>Une photo de toi</li>
        <li>Taille de T-shirt</li>
      </ul>
      <hr>
      <p>Avantages :&nbsp;</p>
      <ul>
        <li>Si tu le souhaites, tu pourras dormir au camping (place garantie au camping regular)</li>
        <li>Tu b&eacute;n&eacute;ficieras de 2 collations et 3 boissons chaque jour &agrave; l'espace b&eacute;n&eacute;vole.</li>
        <li>Tu b&eacute;n&eacute;ficieras d&rsquo;un acc&egrave;s au festival et tu pourras en profiter en dehors de tes horaires de travail.</li>
      </ul>
    </div>
  </div>
</div>

app/templates/pages/account.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <table>
        <tr valign="top">
            <td><img src="{{ user.avatar(64) }}"></td>
            <td>
                <h1>Utilisateur : {{ user.last_name }} {{ user.first_name }}</h1>
                <p>Adresse : {{ user.address }}</p>
                <p>Email : {{ user.email }}</p>
                Tes rôles : 
                {% for role in user.roles %}
                    <p> - {{ role.label }}</p>
                {% endfor %}
            </td>         
        </tr>
    </table>

    Modifie ton profil : <a href="{{ url_for('account.edit_user') }}">ici</a>

{% endblock %}

app/templates/pages/index.jinja2
{% extends "base.jinja2" %}

{% block content %}
{% include 'pages/_reglement.html' %}
{% endblock %}